[tool.poetry]
name = "streamlit-llm"
version = "0.1.0"
description = ""
authors = ["yongwoon <yonyon.japan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.41.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
